<?php

namespace App\Modules\Country\Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Modules\Country\Models\Country;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $timestamp = Carbon::now();

        $countries = [
            ['name' => 'Afghanistan', 'iso_code' => 'AF', 'phone_code' => '93'],
            ['name' => 'Albania', 'iso_code' => 'AL', 'phone_code' => '355'],
            ['name' => 'Algeria', 'iso_code' => 'DZ', 'phone_code' => '213'],
            ['name' => 'Andorra', 'iso_code' => 'AD', 'phone_code' => '376'],
            ['name' => 'Angola', 'iso_code' => 'AO', 'phone_code' => '244'],
            ['name' => 'Antigua and Barbuda', 'iso_code' => 'AG', 'phone_code' => '1-268'],
            ['name' => 'Argentina', 'iso_code' => 'AR', 'phone_code' => '54'],
            ['name' => 'Armenia', 'iso_code' => 'AM', 'phone_code' => '374'],
            ['name' => 'Australia', 'iso_code' => 'AU', 'phone_code' => '61'],
            ['name' => 'Austria', 'iso_code' => 'AT', 'phone_code' => '43'],
            ['name' => 'Azerbaijan', 'iso_code' => 'AZ', 'phone_code' => '994'],
            ['name' => 'Bahamas', 'iso_code' => 'BS', 'phone_code' => '1-242'],
            ['name' => 'Bahrain', 'iso_code' => 'BH', 'phone_code' => '973'],
            ['name' => 'Bangladesh', 'iso_code' => 'BD', 'phone_code' => '880'],
            ['name' => 'Barbados', 'iso_code' => 'BB', 'phone_code' => '1-246'],
            ['name' => 'Belarus', 'iso_code' => 'BY', 'phone_code' => '375'],
            ['name' => 'Belgium', 'iso_code' => 'BE', 'phone_code' => '32'],
            ['name' => 'Belize', 'iso_code' => 'BZ', 'phone_code' => '501'],
            ['name' => 'Benin', 'iso_code' => 'BJ', 'phone_code' => '229'],
            ['name' => 'Bhutan', 'iso_code' => 'BT', 'phone_code' => '975'],
            ['name' => 'Bolivia', 'iso_code' => 'BO', 'phone_code' => '591'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'BA', 'phone_code' => '387'],
            ['name' => 'Botswana', 'iso_code' => 'BW', 'phone_code' => '267'],
            ['name' => 'Brazil', 'iso_code' => 'BR', 'phone_code' => '55'],
            ['name' => 'Brunei', 'iso_code' => 'BN', 'phone_code' => '673'],
            ['name' => 'Bulgaria', 'iso_code' => 'BG', 'phone_code' => '359'],
            ['name' => 'Burkina Faso', 'iso_code' => 'BF', 'phone_code' => '226'],
            ['name' => 'Burundi', 'iso_code' => 'BI', 'phone_code' => '257'],
            ['name' => 'Cambodia', 'iso_code' => 'KH', 'phone_code' => '855'],
            ['name' => 'Cameroon', 'iso_code' => 'CM', 'phone_code' => '237'],
            ['name' => 'Canada', 'iso_code' => 'CA', 'phone_code' => '1'],
            ['name' => 'Cape Verde', 'iso_code' => 'CV', 'phone_code' => '238'],
            ['name' => 'Central African Republic', 'iso_code' => 'CF', 'phone_code' => '236'],
            ['name' => 'Chad', 'iso_code' => 'TD', 'phone_code' => '235'],
            ['name' => 'Chile', 'iso_code' => 'CL', 'phone_code' => '56'],
            ['name' => 'China', 'iso_code' => 'CN', 'phone_code' => '86'],
            ['name' => 'Colombia', 'iso_code' => 'CO', 'phone_code' => '57'],
            ['name' => 'Comoros', 'iso_code' => 'KM', 'phone_code' => '269'],
            ['name' => 'Congo (Brazzaville)', 'iso_code' => 'CG', 'phone_code' => '242'],
            ['name' => 'Congo (Kinshasa)', 'iso_code' => 'CD', 'phone_code' => '243'],
            ['name' => 'Costa Rica', 'iso_code' => 'CR', 'phone_code' => '506'],
            ['name' => 'Croatia', 'iso_code' => 'HR', 'phone_code' => '385'],
            ['name' => 'Cuba', 'iso_code' => 'CU', 'phone_code' => '53'],
            ['name' => 'Cyprus', 'iso_code' => 'CY', 'phone_code' => '357'],
            ['name' => 'Czech Republic', 'iso_code' => 'CZ', 'phone_code' => '420'],
            ['name' => 'Denmark', 'iso_code' => 'DK', 'phone_code' => '45'],
            ['name' => 'Djibouti', 'iso_code' => 'DJ', 'phone_code' => '253'],
            ['name' => 'Dominica', 'iso_code' => 'DM', 'phone_code' => '1-767'],
            ['name' => 'Dominican Republic', 'iso_code' => 'DO', 'phone_code' => '1-809'],
            ['name' => 'Ecuador', 'iso_code' => 'EC', 'phone_code' => '593'],
            ['name' => 'Egypt', 'iso_code' => 'EG', 'phone_code' => '20'],
            ['name' => 'El Salvador', 'iso_code' => 'SV', 'phone_code' => '503'],
            ['name' => 'Equatorial Guinea', 'iso_code' => 'GQ', 'phone_code' => '240'],
            ['name' => 'Eritrea', 'iso_code' => 'ER', 'phone_code' => '291'],
            ['name' => 'Estonia', 'iso_code' => 'EE', 'phone_code' => '372'],
            ['name' => 'Eswatini', 'iso_code' => 'SZ', 'phone_code' => '268'],
            ['name' => 'Ethiopia', 'iso_code' => 'ET', 'phone_code' => '251'],
            ['name' => 'Fiji', 'iso_code' => 'FJ', 'phone_code' => '679'],
            ['name' => 'Finland', 'iso_code' => 'FI', 'phone_code' => '358'],
            ['name' => 'France', 'iso_code' => 'FR', 'phone_code' => '33'],
            ['name' => 'Gabon', 'iso_code' => 'GA', 'phone_code' => '241'],
            ['name' => 'Gambia', 'iso_code' => 'GM', 'phone_code' => '220'],
            ['name' => 'Georgia', 'iso_code' => 'GE', 'phone_code' => '995'],
            ['name' => 'Germany', 'iso_code' => 'DE', 'phone_code' => '49'],
            ['name' => 'Ghana', 'iso_code' => 'GH', 'phone_code' => '233'],
            ['name' => 'Greece', 'iso_code' => 'GR', 'phone_code' => '30'],
            ['name' => 'Grenada', 'iso_code' => 'GD', 'phone_code' => '1-473'],
            ['name' => 'Guatemala', 'iso_code' => 'GT', 'phone_code' => '502'],
            ['name' => 'Guinea', 'iso_code' => 'GN', 'phone_code' => '224'],
            ['name' => 'Guinea-Bissau', 'iso_code' => 'GW', 'phone_code' => '245'],
            ['name' => 'Guyana', 'iso_code' => 'GY', 'phone_code' => '592'],
            ['name' => 'Haiti', 'iso_code' => 'HT', 'phone_code' => '509'],
            ['name' => 'Honduras', 'iso_code' => 'HN', 'phone_code' => '504'],
            ['name' => 'Hungary', 'iso_code' => 'HU', 'phone_code' => '36'],
            ['name' => 'Iceland', 'iso_code' => 'IS', 'phone_code' => '354'],
            ['name' => 'India', 'iso_code' => 'IN', 'phone_code' => '91'],
            ['name' => 'Indonesia', 'iso_code' => 'ID', 'phone_code' => '62'],
            ['name' => 'Iran', 'iso_code' => 'IR', 'phone_code' => '98'],
            ['name' => 'Iraq', 'iso_code' => 'IQ', 'phone_code' => '964'],
            ['name' => 'Ireland', 'iso_code' => 'IE', 'phone_code' => '353'],
            ['name' => 'Israel', 'iso_code' => 'IL', 'phone_code' => '972'],
            ['name' => 'Italy', 'iso_code' => 'IT', 'phone_code' => '39'],
            ['name' => 'Jamaica', 'iso_code' => 'JM', 'phone_code' => '1-876'],
            ['name' => 'Japan', 'iso_code' => 'JP', 'phone_code' => '81'],
            ['name' => 'Jordan', 'iso_code' => 'JO', 'phone_code' => '962'],
            ['name' => 'Kazakhstan', 'iso_code' => 'KZ', 'phone_code' => '7'],
            ['name' => 'Kenya', 'iso_code' => 'KE', 'phone_code' => '254'],
            ['name' => 'Kiribati', 'iso_code' => 'KI', 'phone_code' => '686'],
            ['name' => 'Kuwait', 'iso_code' => 'KW', 'phone_code' => '965'],
            ['name' => 'Kyrgyzstan', 'iso_code' => 'KG', 'phone_code' => '996'],
            ['name' => 'Laos', 'iso_code' => 'LA', 'phone_code' => '856'],
            ['name' => 'Latvia', 'iso_code' => 'LV', 'phone_code' => '371'],
            ['name' => 'Lebanon', 'iso_code' => 'LB', 'phone_code' => '961'],
            ['name' => 'Lesotho', 'iso_code' => 'LS', 'phone_code' => '266'],
            ['name' => 'Liberia', 'iso_code' => 'LR', 'phone_code' => '231'],
            ['name' => 'Libya', 'iso_code' => 'LY', 'phone_code' => '218'],
            ['name' => 'Liechtenstein', 'iso_code' => 'LI', 'phone_code' => '423'],
            ['name' => 'Lithuania', 'iso_code' => 'LT', 'phone_code' => '370'],
            ['name' => 'Luxembourg', 'iso_code' => 'LU', 'phone_code' => '352'],
            ['name' => 'Madagascar', 'iso_code' => 'MG', 'phone_code' => '261'],
            ['name' => 'Malawi', 'iso_code' => 'MW', 'phone_code' => '265'],
            ['name' => 'Malaysia', 'iso_code' => 'MY', 'phone_code' => '60'],
            ['name' => 'Maldives', 'iso_code' => 'MV', 'phone_code' => '960'],
            ['name' => 'Mali', 'iso_code' => 'ML', 'phone_code' => '223'],
            ['name' => 'Malta', 'iso_code' => 'MT', 'phone_code' => '356'],
            ['name' => 'Marshall Islands', 'iso_code' => 'MH', 'phone_code' => '692'],
            ['name' => 'Mauritania', 'iso_code' => 'MR', 'phone_code' => '222'],
            ['name' => 'Mauritius', 'iso_code' => 'MU', 'phone_code' => '230'],
            ['name' => 'Mexico', 'iso_code' => 'MX', 'phone_code' => '52'],
            ['name' => 'Micronesia', 'iso_code' => 'FM', 'phone_code' => '691'],
            ['name' => 'Moldova', 'iso_code' => 'MD', 'phone_code' => '373'],
            ['name' => 'Monaco', 'iso_code' => 'MC', 'phone_code' => '377'],
            ['name' => 'Mongolia', 'iso_code' => 'MN', 'phone_code' => '976'],
            ['name' => 'Montenegro', 'iso_code' => 'ME', 'phone_code' => '382'],
            ['name' => 'Morocco', 'iso_code' => 'MA', 'phone_code' => '212'],
            ['name' => 'Mozambique', 'iso_code' => 'MZ', 'phone_code' => '258'],
            ['name' => 'Myanmar', 'iso_code' => 'MM', 'phone_code' => '95'],
            ['name' => 'Namibia', 'iso_code' => 'NA', 'phone_code' => '264'],
            ['name' => 'Nauru', 'iso_code' => 'NR', 'phone_code' => '674'],
            ['name' => 'Nepal', 'iso_code' => 'NP', 'phone_code' => '977'],
            ['name' => 'Netherlands', 'iso_code' => 'NL', 'phone_code' => '31'],
            ['name' => 'New Zealand', 'iso_code' => 'NZ', 'phone_code' => '64'],
            ['name' => 'Nicaragua', 'iso_code' => 'NI', 'phone_code' => '505'],
            ['name' => 'Niger', 'iso_code' => 'NE', 'phone_code' => '227'],
            ['name' => 'Nigeria', 'iso_code' => 'NG', 'phone_code' => '234'],
            ['name' => 'North Korea', 'iso_code' => 'KP', 'phone_code' => '850'],
            ['name' => 'North Macedonia', 'iso_code' => 'MK', 'phone_code' => '389'],
            ['name' => 'Norway', 'iso_code' => 'NO', 'phone_code' => '47'],
            ['name' => 'Oman', 'iso_code' => 'OM', 'phone_code' => '968'],
            ['name' => 'Pakistan', 'iso_code' => 'PK', 'phone_code' => '92'],
            ['name' => 'Palau', 'iso_code' => 'PW', 'phone_code' => '680'],
            ['name' => 'Palestine', 'iso_code' => 'PS', 'phone_code' => '970'],
            ['name' => 'Panama', 'iso_code' => 'PA', 'phone_code' => '507'],
            ['name' => 'Papua New Guinea', 'iso_code' => 'PG', 'phone_code' => '675'],
            ['name' => 'Paraguay', 'iso_code' => 'PY', 'phone_code' => '595'],
            ['name' => 'Peru', 'iso_code' => 'PE', 'phone_code' => '51'],
            ['name' => 'Philippines', 'iso_code' => 'PH', 'phone_code' => '63'],
            ['name' => 'Poland', 'iso_code' => 'PL', 'phone_code' => '48'],
            ['name' => 'Portugal', 'iso_code' => 'PT', 'phone_code' => '351'],
            ['name' => 'Qatar', 'iso_code' => 'QA', 'phone_code' => '974'],
            ['name' => 'Romania', 'iso_code' => 'RO', 'phone_code' => '40'],
            ['name' => 'Russia', 'iso_code' => 'RU', 'phone_code' => '7'],
            ['name' => 'Rwanda', 'iso_code' => 'RW', 'phone_code' => '250'],
            ['name' => 'Saint Kitts and Nevis', 'iso_code' => 'KN', 'phone_code' => '1-869'],
            ['name' => 'Saint Lucia', 'iso_code' => 'LC', 'phone_code' => '1-758'],
            ['name' => 'Saint Vincent and the Grenadines', 'iso_code' => 'VC', 'phone_code' => '1-784'],
            ['name' => 'Samoa', 'iso_code' => 'WS', 'phone_code' => '685'],
            ['name' => 'San Marino', 'iso_code' => 'SM', 'phone_code' => '378'],
            ['name' => 'Sao Tome and Principe', 'iso_code' => 'ST', 'phone_code' => '239'],
            ['name' => 'Saudi Arabia', 'iso_code' => 'SA', 'phone_code' => '966'],
            ['name' => 'Senegal', 'iso_code' => 'SN', 'phone_code' => '221'],
            ['name' => 'Serbia', 'iso_code' => 'RS', 'phone_code' => '381'],
            ['name' => 'Seychelles', 'iso_code' => 'SC', 'phone_code' => '248'],
            ['name' => 'Sierra Leone', 'iso_code' => 'SL', 'phone_code' => '232'],
            ['name' => 'Singapore', 'iso_code' => 'SG', 'phone_code' => '65'],
            ['name' => 'Slovakia', 'iso_code' => 'SK', 'phone_code' => '421'],
            ['name' => 'Slovenia', 'iso_code' => 'SI', 'phone_code' => '386'],
            ['name' => 'Solomon Islands', 'iso_code' => 'SB', 'phone_code' => '677'],
            ['name' => 'Somalia', 'iso_code' => 'SO', 'phone_code' => '252'],
            ['name' => 'South Africa', 'iso_code' => 'ZA', 'phone_code' => '27'],
            ['name' => 'South Korea', 'iso_code' => 'KR', 'phone_code' => '82'],
            ['name' => 'South Sudan', 'iso_code' => 'SS', 'phone_code' => '211'],
            ['name' => 'Spain', 'iso_code' => 'ES', 'phone_code' => '34'],
            ['name' => 'Sri Lanka', 'iso_code' => 'LK', 'phone_code' => '94'],
            ['name' => 'Sudan', 'iso_code' => 'SD', 'phone_code' => '249'],
            ['name' => 'Suriname', 'iso_code' => 'SR', 'phone_code' => '597'],
            ['name' => 'Sweden', 'iso_code' => 'SE', 'phone_code' => '46'],
            ['name' => 'Switzerland', 'iso_code' => 'CH', 'phone_code' => '41'],
            ['name' => 'Syria', 'iso_code' => 'SY', 'phone_code' => '963'],
            ['name' => 'Taiwan', 'iso_code' => 'TW', 'phone_code' => '886'],
            ['name' => 'Tajikistan', 'iso_code' => 'TJ', 'phone_code' => '992'],
            ['name' => 'Tanzania', 'iso_code' => 'TZ', 'phone_code' => '255'],
            ['name' => 'Thailand', 'iso_code' => 'TH', 'phone_code' => '66'],
            ['name' => 'Timor-Leste', 'iso_code' => 'TL', 'phone_code' => '670'],
            ['name' => 'Togo', 'iso_code' => 'TG', 'phone_code' => '228'],
            ['name' => 'Tonga', 'iso_code' => 'TO', 'phone_code' => '676'],
            ['name' => 'Trinidad and Tobago', 'iso_code' => 'TT', 'phone_code' => '1-868'],
            ['name' => 'Tunisia', 'iso_code' => 'TN', 'phone_code' => '216'],
            ['name' => 'Turkey', 'iso_code' => 'TR', 'phone_code' => '90'],
            ['name' => 'Turkmenistan', 'iso_code' => 'TM', 'phone_code' => '993'],
            ['name' => 'Tuvalu', 'iso_code' => 'TV', 'phone_code' => '688'],
            ['name' => 'Uganda', 'iso_code' => 'UG', 'phone_code' => '256'],
            ['name' => 'Ukraine', 'iso_code' => 'UA', 'phone_code' => '380'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'AE', 'phone_code' => '971'],
            ['name' => 'United Kingdom', 'iso_code' => 'GB', 'phone_code' => '44'],
            ['name' => 'United States', 'iso_code' => 'US', 'phone_code' => '1'],
            ['name' => 'Uruguay', 'iso_code' => 'UY', 'phone_code' => '598'],
            ['name' => 'Uzbekistan', 'iso_code' => 'UZ', 'phone_code' => '998'],
            ['name' => 'Vanuatu', 'iso_code' => 'VU', 'phone_code' => '678'],
            ['name' => 'Vatican City', 'iso_code' => 'VA', 'phone_code' => '379'],
            ['name' => 'Venezuela', 'iso_code' => 'VE', 'phone_code' => '58'],
            ['name' => 'Vietnam', 'iso_code' => 'VN', 'phone_code' => '84'],
            ['name' => 'Yemen', 'iso_code' => 'YE', 'phone_code' => '967'],
            ['name' => 'Zambia', 'iso_code' => 'ZM', 'phone_code' => '260'],
            ['name' => 'Zimbabwe', 'iso_code' => 'ZW', 'phone_code' => '263'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name' => $country['name'],
                'iso_code' => $country['iso_code'],
                'phone_code' => $country['phone_code'],
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ]);
        }
    }
}
