<?php

namespace App\Modules\Currency\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $currencies = [
            [
                'name' => 'United States Dollar',
                'code' => 'USD',
                'symbol' => '$',
                'country' => 'United States',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indian Rupee',
                'code' => 'INR',
                'symbol' => '₹',
                'country' => 'India',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pound Sterling',
                'code' => 'GBP',
                'symbol' => '£',
                'country' => 'United Kingdom',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Canadian Dollar',
                'code' => 'CAD',
                'symbol' => '$',
                'country' => 'Canada',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'symbol' => '$',
                'country' => 'Australia',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Japanese Yen',
                'code' => 'JPY',
                'symbol' => '¥',
                'country' => 'Japan',
                'exchange_rate' => null,
                'decimal_places' => '0',
                'status' => 'active',
                'format' => '1,234',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chinese Yuan Renminbi',
                'code' => 'CNY',
                'symbol' => '¥',
                'country' => 'China',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country' => 'Germany',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country' => 'France',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country' => 'Italy',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Russian Ruble',
                'code' => 'RUB',
                'symbol' => '₽',
                'country' => 'Russia',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1 234,56',
                'thousands_separator' => ' ',
                'decimal_separator' => ',',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brazilian Real',
                'code' => 'BRL',
                'symbol' => 'R$',
                'country' => 'Brazil',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South African Rand',
                'code' => 'ZAR',
                'symbol' => 'R',
                'country' => 'South Africa',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Saudi Riyal',
                'code' => 'SAR',
                'symbol' => 'SR',
                'country' => 'Saudi Arabia',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Argentine Peso',
                'code' => 'ARS',
                'symbol' => '$',
                'country' => 'Argentina',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Swiss Franc',
                'code' => 'CHF',
                'symbol' => 'CHF',
                'country' => 'Switzerland',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1\'234.56',
                'thousands_separator' => '\'',
                'decimal_separator' => '.',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'South Korean Won',
                'code' => 'KRW',
                'symbol' => '₩',
                'country' => 'South Korea',
                'exchange_rate' => null,
                'decimal_places' => '0',
                'status' => 'active',
                'format' => '1,234',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mexican Peso',
                'code' => 'MXN',
                'symbol' => '$',
                'country' => 'Mexico',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Indonesian Rupiah',
                'code' => 'IDR',
                'symbol' => 'Rp',
                'country' => 'Indonesia',
                'exchange_rate' => null,
                'decimal_places' => '0',
                'status' => 'active',
                'format' => '1.234',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Turkish Lira',
                'code' => 'TRY',
                'symbol' => '₺',
                'country' => 'Turkey',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UAE Dirham',
                'code' => 'AED',
                'symbol' => 'DH',
                'country' => 'United Arab Emirates',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pakistani Rupee',
                'code' => 'PKR',
                'symbol' => '₨',
                'country' => 'Pakistan',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bangladeshi Taka',
                'code' => 'BDT',
                'symbol' => '৳',
                'country' => 'Bangladesh',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vietnamese Dong',
                'code' => 'VND',
                'symbol' => '₫',
                'country' => 'Vietnam',
                'exchange_rate' => null,
                'decimal_places' => '0',
                'status' => 'active',
                'format' => '1,234',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nigerian Naira',
                'code' => 'NGN',
                'symbol' => '₦',
                'country' => 'Nigeria',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Malaysian Ringgit',
                'code' => 'MYR',
                'symbol' => 'RM',
                'country' => 'Malaysia',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thai Baht',
                'code' => 'THB',
                'symbol' => '฿',
                'country' => 'Thailand',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Singapore Dollar',
                'code' => 'SGD',
                'symbol' => 'S$',
                'country' => 'Singapore',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ukrainian Hryvnia',
                'code' => 'UAH',
                'symbol' => '₴',
                'country' => 'Ukraine',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1 234,56',
                'thousands_separator' => ' ',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Egyptian Pound',
                'code' => 'EGP',
                'symbol' => '£',
                'country' => 'Egypt',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Iranian Rial',
                'code' => 'IRR',
                'symbol' => '﷼',
                'country' => 'Iran',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Afghan Afghani',
                'code' => 'AFN',
                'symbol' => '؋',
                'country' => 'Afghanistan',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nepalese Rupee',
                'code' => 'NPR',
                'symbol' => '₨',
                'country' => 'Nepal',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sri Lankan Rupee',
                'code' => 'LKR',
                'symbol' => '₨',
                'country' => 'Sri Lanka',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bhutanese Ngultrum',
                'code' => 'BTN',
                'symbol' => 'Nu.',
                'country' => 'Bhutan',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maldivian Rufiyaa',
                'code' => 'MVR',
                'symbol' => 'Rf',
                'country' => 'Maldives',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Polish Zloty',
                'code' => 'PLN',
                'symbol' => 'zł',
                'country' => 'Poland',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1 234,56',
                'thousands_separator' => ' ',
                'decimal_separator' => ',',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Czech Koruna',
                'code' => 'CZK',
                'symbol' => 'Kč',
                'country' => 'Czech Republic',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1 234,56',
                'thousands_separator' => ' ',
                'decimal_separator' => ',',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Swedish Krona',
                'code' => 'SEK',
                'symbol' => 'kr',
                'country' => 'Sweden',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1 234,56',
                'thousands_separator' => ' ',
                'decimal_separator' => ',',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Norwegian Krone',
                'code' => 'NOK',
                'symbol' => 'kr',
                'country' => 'Norway',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1 234,56',
                'thousands_separator' => ' ',
                'decimal_separator' => ',',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Danish Krone',
                'code' => 'DKK',
                'symbol' => 'kr.',
                'country' => 'Denmark',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'after',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Qatari Riyal',
                'code' => 'QAR',
                'symbol' => 'QR',
                'country' => 'Qatar',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Israeli Shekel',
                'code' => 'ILS',
                'symbol' => '₪',
                'country' => 'Israel',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'symbol' => '$',
                'country' => 'New Zealand',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country' => 'Portugal',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Euro',
                'code' => 'EUR',
                'symbol' => '€',
                'country' => 'Spain',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1.234,56',
                'thousands_separator' => '.',
                'decimal_separator' => ',',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kenyan Shilling',
                'code' => 'KES',
                'symbol' => 'KSh',
                'country' => 'Kenya',
                'exchange_rate' => null,
                'decimal_places' => '2',
                'status' => 'active',
                'format' => '1,234.56',
                'thousands_separator' => ',',
                'decimal_separator' => '.',
                'symbol_position' => 'before',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($currencies as $currency) {
            DB::table('currencies')->updateOrInsert(
                ['code' => $currency['code']],
                $currency
            );
        }
    }
}
